### ISSUE TITLE
Don't commit this file

### ISSUE THREAD

**Issue by gayangithub** [migdbdev/migdbclient#77]
please don't commit this  [INTERNAL_DB.db](https://github.com/migdbdev/migdbclient/commit/d84ad5cfe405bec24c7612ea055b1790fbbc574e)

**Comment by Kanishkalahiru** [comment]
I'm not commit it

**Comment by gayangithub** [comment]
Then why that commit say INTERNAL_DB.db changed by your commit
![screen shot](https://cloud.githubusercontent.com/assets/6977493/17052254/4ab0b674-501a-11e6-81a4-78d19083db66.PNG)
